In [16]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn import datasets
import random

In [17]:
iris = datasets.load_iris()
X = iris.data[:, :2]
length = X.shape[0]
#print(length)
y = []
for i in range(length):
    y.append([0, 0])
#print(y.shape[0])

k=3
CentreIndex = list(random.sample(range(0, length), k))
print(CentreIndex)

Centres = []
for i in range(k):
    Centres.append(list(X[CentreIndex[i]]))
    
print(Centres)

[127, 113, 65]
[[6.1, 3.0], [5.7, 2.5], [6.7, 3.1]]


In [18]:
for i in range(5) :
    print(X[i,:])
    

[5.1 3.5]
[4.9 3. ]
[4.7 3.2]
[4.6 3.1]
[5.  3.6]


In [19]:
counter = 0
while counter<100 :
    distances = np.zeros((length, 3))
    lengths = []
    for i in range(k):
        lengths.append(0)

    for i in range(length):
        for j in range(k):
            distances[i][j] = ((Centres[j][0] - X[i][0])**2 + (Centres[j][1] - X[i][1])**2)**(0.5)
        
    print('Distances:')
    for i in range(5):
        print(distances[i])
        
    for i in range(length):
        minimum = distances[i][0]
        minIndex = 0
        for j in range(k):
            if minimum>distances[i][j]:
                minimum = distances[i][j]
                minIndex = j
        
        #print('Centres:')
        #rint(Centres[minIndex])
        y[i] = list(Centres[minIndex])
        lengths[minIndex] += 1
    
    print('y:')
    for i in range(5):
        print(y[i])
    
    lossDistance = [0, 0]
    for i in range(length):
        lossDistance[0] += y[i][0] - X[i][0]
        if lossDistance[0]<0 :
            lossDistance[0] *= -1
        
        lossDistance[1] += y[i][1] - X[i][1]
        if lossDistance[1]<0 :
            lossDistance[1] *= -1
            
    print('Loss Distance: ')
    print(lossDistance[0] + lossDistance[1])
    
    avg = np.zeros((k, 2))

    for i in range(length):
        index = 0
        for j in range(k):
            if y[i] == Centres[j]:
                index = j
                #print('Index: ')
                #print(index)
                #print('Value: ')
                #print(y[i])
                #print('Centre: ')
                #print(Centres[j])
    
        avg[index][0] += X[i][0]
        avg[index][1] += X[i][1]

    flag = 0
    for i in range(k):
        avg[i][0] /= lengths[i]
        avg[i][0] = round(avg[i][0], 2)
        avg[i][1] /= lengths[i]
        avg[i][1] = round(avg[i][1], 2)
        if avg[i][0] != Centres[i][0] or avg[i][1] != Centres[i][1] :
            flag = 1
            
   
    #print('Average:')
    #print(avg)
    print(flag)

    if flag==1:
        for i in range(k):
            Centres[i][0]=round(avg[i][0], 2)
            Centres[i][1]=round(avg[i][1], 2)
    else:
        print('Centres:')
        print(Centres)
        break
    
    print('Centres:')
    print(Centres)
    
    counter += 1

Distances:
[1.11803399 1.16619038 1.64924225]
[1.2        0.94339811 1.80277564]
[1.41421356 1.22065556 2.00249844]
[1.50332964 1.25299641 2.1       ]
[1.25299641 1.30384048 1.77200451]
y:
[6.1, 3.0]
[5.7, 2.5]
[5.7, 2.5]
[5.7, 2.5]
[6.1, 3.0]
Loss Distance: 
39.89999999999999
1
Centres:
[[5.76, 3.27], [5.21, 2.83], [6.93, 3.08]]
Distances:
[0.69892775 0.67896981 1.87757823]
[0.90138782 0.35355339 2.03157574]
[1.06230881 0.63007936 2.23322637]
[1.17239072 0.6670832  2.33008584]
[0.82855296 0.7981228  1.99882465]
y:
[5.21, 2.83]
[5.21, 2.83]
[5.21, 2.83]
[5.21, 2.83]
[5.21, 2.83]
Loss Distance: 
35.69999999999998
1
Centres:
[[5.76, 3.25], [5.07, 2.94], [6.8, 2.98]]
Distances:
[0.705762   0.560803   1.77775139]
[0.89560036 0.18027756 1.90010526]
[1.06117859 0.45221676 2.11149236]
[1.16965807 0.49648766 2.2032703 ]
[0.83671979 0.66370174 1.9037857 ]
y:
[5.07, 2.94]
[5.07, 2.94]
[5.07, 2.94]
[5.07, 2.94]
[5.07, 2.94]
Loss Distance: 
27.299999999999997
1
Centres:
[[5.76, 3.15], [4.96, 3.03]